import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  components: [
    {
      type: 'category',
      label: 'Getting started',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'ui' }],
    },
  ],
};

export default sidebars;

