import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  components: [
    {
      type: 'category',
      label: 'Getting started',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'components' }],
    },
    {
      type: 'category',
      label: 'Pages',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'pages' }],
    },
  ],
};

export default sidebars;

