name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]

# Needed so the action can push to gh-pages
permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm   # change to "yarn" if you use yarn

      - name: Install deps
        run: npm ci
        # If you use yarn:
        # run: yarn --frozen-lockfile

      - name: Build Docusaurus
        run: npm run build
        # If your build script isn't set, add to package.json:
        # "scripts": { "build": "docusaurus build" }

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          # Optional but common:
          force_orphan: true
